package Balai;

/**
 * Created by Sami on 01/12/2016.
 */
/*
public enum TypeSortilege extends Type {
    TONNEAU,RECTIFICATION,VOLINVERSE,ATTRACTION,DOUBLEJEU,VENTARRIERE,OUTILREPARE,DECRET,BLOCAGE,
    MAUVAISSORT,BROUILLARDMAGIQUE,LOOPING
}*/
